version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1

on:
  pull_request:
    types: [closed]
    
jobs:
  create-cf-stack:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:          
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_REGION_NAME
      - run: >-
          aws cloudformation create-stack --stack-name greens3cfci --template-body file://green_cf_template.json
workflows:
  aws-cli:
    jobs:
      - create-cf-stack
